CREATE TABLE Customer
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     varchar(30)  NOT NULL UNIQUE,
    email        varchar(255) NOT NULL,
    password     varchar(255) NOT NULL,
    customerRole varchar(255) NOT NULL
);
CREATE TABLE Item
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);
CREATE TABLE Product
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id int         REFERENCES Item (id) ON DELETE SET NULL,
    size    varchar(50) NOT NULL,
    color   varchar(50) NOT NULL,
    price   int         NOT NULL
);
CREATE TABLE Address
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     int REFERENCES Customer (id) ON DELETE CASCADE,
    country     varchar(255) NOT NULL,
    city        varchar(255) NOT NULL,
    state       varchar(255) NOT NULL,
    firstname   varchar(255) NOT NULL,
    lastname    varchar(255) NOT NULL,
    zipcode     int          NOT NULL,
    phoneNumber bigint       NOT NULL
);
CREATE TABLE Cart
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES Customer (id) ON DELETE CASCADE
);
CREATE TABLE CartProduct
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    int REFERENCES Cart (id) ON DELETE CASCADE,
    product_id int REFERENCES Product (id) ON DELETE CASCADE,
    quantity   int NOT NULL
);
CREATE TABLE Ord
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    int REFERENCES Customer (id) ON DELETE CASCADE,
    address_id int REFERENCES Address (id) ON DELETE CASCADE,
    status     varchar(50) NOT NULL,
    orderedAt  timestamp
);
CREATE TABLE OrdProduct
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   int REFERENCES Ord (id) ON DELETE CASCADE,
    product_id int REFERENCES Product (id) ON DELETE CASCADE,
    quantity   int NOT NULL
);






