CREATE TABLE Customer
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     varchar(30)  NOT NULL UNIQUE,
    fullname     varchar(30)  NOT NULL,
    email        varchar(255) NOT NULL,
    password     varchar(255) NOT NULL,
    customerRole varchar(255) NOT NULL
);
CREATE TABLE Product
(
    id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    size    varchar(50) NOT NULL,
    color   varchar(50) NOT NULL,
    quantity int        NOT NULL,
    price   int         NOT NULL
);
CREATE TABLE Address
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     int REFERENCES Customer (id) ON DELETE CASCADE,
    country     varchar(255) NOT NULL,
    city        varchar(255) NOT NULL,
    state       varchar(255) NOT NULL,
    firstname   varchar(255) NOT NULL,
    lastname    varchar(255) NOT NULL,
    zipcode     int          NOT NULL,
    phoneNumber bigint       NOT NULL
);
CREATE TABLE CartProduct
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id int REFERENCES Product (id) ON DELETE CASCADE,
    customer_id int REFERENCES Customer (id) ON DELETE CASCADE,
    quantity   int NOT NULL
);
CREATE TABLE Ord
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    int REFERENCES Customer (id) ON DELETE CASCADE,
    address_id int REFERENCES Address (id) ON DELETE CASCADE,
    status     varchar(50) NOT NULL,
    orderedAt  timestamp
);
CREATE TABLE OrdProduct
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ord_id   int REFERENCES Ord (id) ON DELETE CASCADE,
    product_id int REFERENCES Product (id) ON DELETE CASCADE,
    quantity   int NOT NULL
);






